CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "email" varchar(100) UNIQUE NOT NULL,
  "status" boolean DEFAULT false,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "phones" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phone" varchar(15) UNIQUE NOT NULL,
  "user_id" integer,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "content" text NOT NULL,
  "user_id" integer,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "price" integer DEFAULT 0,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "users_courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "courses_id" integer,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

ALTER TABLE "phones" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "users_courses" ADD FOREIGN KEY ("courses_id") REFERENCES "courses" ("id");
